### ISSUE TITLE
error behind nginx

### ISSUE THREAD

**Issue by targaro91** [Doridian/wsvpn#175]
Everything works well for me when a direct connection is realized between client and server, but when I have the server behind NGINX, an error on the client's side occurs.

Config nginx:

server {
    listen 443 ssl;
    server_name test.lacbay.alinet.cu
     ssl_certificate /home/admin/*****;
     ssl_certificate_key /home/admin/****;

    location / {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_pass https://192.168.10.1:9000;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
}

Log Server: 
2023/03/23 07:42:53 sockets.go:68: [CLIENT-3d747e26-e876-49c0-b413-90731d0aad5b] Authenticated as: client1
2023/03/23 07:42:53 sockets.go:94: [CLIENT-3d747e26-e876-49c0-b413-90731d0aad5b] Upgraded connection to WebSocket
2023/03/23 07:42:53 sockets.go:122: [CLIENT-3d747e26-e876-49c0-b413-90731d0aad5b] Command serialization: json
2023/03/23 07:42:53 sockets.go:263: [CLIENT-3d747e26-e876-49c0-b413-90731d0aad5b] Connection fully established
2023/03/23 07:42:53 base.go:285: [CLIENT-3d747e26-e876-49c0-b413-90731d0aad5b] Adapter ERROR: EOF
2023/03/23 07:42:53 sockets.go:280: [CLIENT-3d747e26-e876-49c0-b413-90731d0aad5b] Disconnected
2023/03/23 07:44:13 sockets.go:49: [CLIENT-408954c8-292d-41c1-8cc5-9fb492a24d9c] TLS 1.2 connection established with cipher=TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256

Log Client:
2023/03/23 13:08:42 Local version is: v5.28.0 (protocol 12)
2023/03/23 13:08:42 base.go:99: [CLIENT-UNSET] Connecting to wss://test.****.com:443 with authentications: HTTP
panic: assignment to entry in nil map

goroutine 1 [running]:
net/textproto.MIMEHeader.Add(...)
        net/textproto/header.go:15
net/http.Header.Add(...)
        net/http/header.go:31
github.com/Doridian/wsvpn/client/connectors.(*WebSocketConnector).Dial.func1({0x11958022, 0x6, 0xfde}, {0x1195802a, 0x15, 0xfd6})
        github.com/Doridian/wsvpn/client/connectors/websocket.go:34 +0xa3
github.com/gobwas/ws.Dialer.Upgrade({0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x59d5b4, ...}, ...}, ...)
        github.com/gobwas/ws@v1.1.0/dialer.go:423 +0x83a
github.com/gobwas/ws.Dialer.Dial({0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x59d5b4, ...}, ...}, ...)
        github.com/gobwas/ws@v1.1.0/dialer.go:190 +0x58e
github.com/Doridian/wsvpn/client/connectors.(*WebSocketConnector).Dial(0x8c07b4, {0x59f3e0, 0x11858870})
        github.com/Doridian/wsvpn/client/connectors/websocket.go:55 +0x1ed
github.com/Doridian/wsvpn/client/clients.(*Client).connectAdapter(0x11858870)
        github.com/Doridian/wsvpn/client/clients/connection.go:49 +0x9d
github.com/Doridian/wsvpn/client/clients.(*Client).Serve(0x11858870)
        github.com/Doridian/wsvpn/client/clients/base.go:101 +0x2f5
github.com/Doridian/wsvpn/client/clients.(*Client).ServeLoop(0x11858870)
        github.com/Doridian/wsvpn/client/clients/base.go:60 +0xf2
github.com/Doridian/wsvpn/client/cli.Main(0x1180aa70, 0x11815648)
        github.com/Doridian/wsvpn/client/cli/base.go:165 +0x412
main.main()
        github.com/Doridian/wsvpn/wsvpn/main.go:24 +0x18e

I don't know much about Goland, but I think the **respHeaders**  variable is being used without initialize.
https://github.com/Doridian/wsvpn/blob/c79d19ddd0121d156637cc9c376d0b68147e6564/client/connectors/websocket.go#L34

**Comment by targaro91** [comment]
With this it is solved, already tested and works perfectly, thanks for this wonderful tool
//var respHeaders http.Header
respHeaders := http.Header{}
https://github.com/Doridian/wsvpn/blob/c79d19ddd0121d156637cc9c376d0b68147e6564/client/connectors/websocket.go#L30
