### ISSUE TITLE
Errors Building version: v5.32.0-31-gbf7152f

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#236]
``` 
Building version: v5.32.0-31-gbf7152f
Cleaning dist...
Generating all build tasks...
Downloading Go modules...
Downloading WinTun from "https://www.wintun.net/builds/wintun-0.14.1.zip"...
Executing build tasks...
Starting: Go build client-linux-amd64
Done: Go build client-linux-amd64
Starting: Go build client-linux-386
Starting: Go build client-linux-arm64
Starting: Go build client-linux-armv5
Starting: Go build client-linux-armv6
Starting: Go build client-linux-armv7
Starting: Go build client-linux-mips
Starting: Go build client-linux-mips-softfloat
Starting: Go build client-linux-mipsle
Done: Go build client-linux-armv5
Starting: Go build client-linux-mipsle-softfloat
Done: Go build client-linux-mips-softfloat
Starting: Go build client-linux-mips64
Done: Go build client-linux-armv6
Starting: Go build client-linux-mips64le
Done: Go build client-linux-mipsle
Starting: Go build client-darwin-amd64
Done: Go build client-linux-arm64
Starting: Go build client-darwin-arm64
Done: Go build client-linux-armv7
Starting: Go build client-windows-amd64.exe
Done: Go build client-linux-mips
Starting: Go build client-windows-386.exe
Done: Go build client-linux-386
Starting: Go build client-windows-arm64.exe
Done: Go build client-linux-mipsle-softfloat
Starting: Go build server-linux-amd64
Done: Go build client-linux-mips64le
Starting: Go build server-linux-386
Done: Go build client-linux-mips64
Starting: Go build server-linux-arm64
Done: Go build client-windows-arm64.exe
Starting: Go build server-linux-armv5
Done: Go build client-windows-amd64.exe
Starting: Go build server-linux-armv6
Done: Go build client-windows-386.exe
Starting: Go build server-linux-armv7
Done: Go build client-darwin-amd64
Starting: Go build server-linux-mips
Done: Go build client-darwin-arm64
Starting: Go build server-linux-mips-softfloat
Done: Go build server-linux-amd64
Starting: Go build server-linux-mipsle
Done: Go build server-linux-armv5
Starting: Go build server-linux-mipsle-softfloat
Done: Go build server-linux-armv6
Starting: Go build server-linux-mips64
Done: Go build server-linux-arm64
Starting: Go build server-linux-mips64le
Done: Go build server-linux-386
Starting: Go build server-darwin-amd64
Done: Go build server-linux-mips
Done: Go build server-linux-armv7
Starting: Go build server-darwin-arm64
Starting: Go build server-windows-amd64.exe
Done: Go build server-linux-mips-softfloat
Starting: Go build server-windows-386.exe
Done: Go build server-linux-mipsle
Starting: Go build server-windows-arm64.exe
Done: Go build server-linux-mips64
Starting: Go build wsvpn-linux-amd64
stat /home/python/Venv/WSVPN/wsvpn/wsvpn: directory not found
Done: Go build wsvpn-linux-amd64
Starting: Go build wsvpn-linux-386
stat /home/python/Venv/WSVPN/wsvpn/wsvpn: directory not found
Done: Go build wsvpn-linux-386
Starting: Go build wsvpn-linux-arm64
stat /home/python/Venv/WSVPN/wsvpn/wsvpn: directory not found
Done: Go build server-linux-mips64le
Starting: Go build wsvpn-linux-armv5
stat /home/python/Venv/WSVPN/wsvpn/wsvpn: directory not found
Done: Go build wsvpn-linux-armv5
Starting: Go build wsvpn-linux-armv6
Done: Go build wsvpn-linux-arm64
Starting: Go build wsvpn-linux-armv7
stat /home/python/Venv/WSVPN/wsvpn/wsvpn: directory not found
Done: Go build wsvpn-linux-armv6
Starting: Go build wsvpn-linux-mips
stat /home/python/Venv/WSVPN/wsvpn/wsvpn: directory not found
Done: Go build server-linux-mipsle-softfloat
Done: Go build wsvpn-linux-armv7
Starting: Go build wsvpn-linux-mips-softfloat
stat /home/python/Venv/WSVPN/wsvpn/wsvpn: directory not found
Done: Go build wsvpn-linux-mips
Starting: Go build wsvpn-linux-mipsle
Starting: Go build wsvpn-linux-mipsle-softfloat
Done: Go build server-windows-amd64.exe
Starting: Go build wsvpn-linux-mips64
stat /home/python/Venv/WSVPN/wsvpn/wsvpn: directory not found
stat /home/python/Venv/WSVPN/wsvpn/wsvpn: directory not found
stat /home/python/Venv/WSVPN/wsvpn/wsvpn: directory not found
Done: Go build wsvpn-linux-mips-softfloat
Done: Go build wsvpn-linux-mipsle
Starting: Go build wsvpn-linux-mips64le
stat /home/python/Venv/WSVPN/wsvpn/wsvpn: directory not found
Done: Go build wsvpn-linux-mipsle-softfloat
stat /home/python/Venv/WSVPN/wsvpn/wsvpn: directory not found
Starting: Go build wsvpn-darwin-amd64
Done: Go build wsvpn-linux-mips64
Done: Go build wsvpn-linux-mips64le
Starting: Go build wsvpn-darwin-arm64
Starting: Go build wsvpn-windows-amd64.exe
Starting: Go build wsvpn-windows-386.exe
stat /home/python/Venv/WSVPN/wsvpn/wsvpn: directory not found
stat /home/python/Venv/WSVPN/wsvpn/wsvpn: directory not found
stat /home/python/Venv/WSVPN/wsvpn/wsvpn: directory not found
Done: Go build wsvpn-darwin-amd64
Done: Go build wsvpn-windows-amd64.exe
Starting: Go build wsvpn-windows-arm64.exe
Done: Go build wsvpn-darwin-arm64
stat /home/python/Venv/WSVPN/wsvpn/wsvpn: directory not found
Done: Go build wsvpn-windows-arm64.exe
stat /home/python/Venv/WSVPN/wsvpn/wsvpn: directory not found
Done: Go build wsvpn-windows-386.exe
Done: Go build server-darwin-amd64
Done: Go build server-darwin-arm64
Done: Go build server-windows-386.exe
Done: Go build server-windows-arm64.exe
Error: Go build wsvpn-linux-amd64
Traceback (most recent call last):
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 473, in main
    task.join()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 204, in join
    raise self.exc
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 192, in run
    self._run()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 227, in _run
    check_call_addenv([self.gocmd, "build", "-trimpath", "-ldflags",
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 148, in check_call_addenv
    return check_call(args, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'build', '-trimpath', '-ldflags', "-w -s -X 'github.com/Doridian/wsvpn/shared.Version=v5.32.0-31-gbf7152f'", '-o', 'dist/wsvpn-linux-amd64', './wsvpn']' returned non-zero exit status 1.
Error: Go build wsvpn-linux-386
Traceback (most recent call last):
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 473, in main
    task.join()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 204, in join
    raise self.exc
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 192, in run
    self._run()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 227, in _run
    check_call_addenv([self.gocmd, "build", "-trimpath", "-ldflags",
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 148, in check_call_addenv
    return check_call(args, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'build', '-trimpath', '-ldflags', "-w -s -X 'github.com/Doridian/wsvpn/shared.Version=v5.32.0-31-gbf7152f'", '-o', 'dist/wsvpn-linux-386', './wsvpn']' returned non-zero exit status 1.
Error: Go build wsvpn-linux-arm64
Traceback (most recent call last):
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 473, in main
    task.join()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 204, in join
    raise self.exc
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 192, in run
    self._run()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 227, in _run
    check_call_addenv([self.gocmd, "build", "-trimpath", "-ldflags",
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 148, in check_call_addenv
    return check_call(args, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'build', '-trimpath', '-ldflags', "-w -s -X 'github.com/Doridian/wsvpn/shared.Version=v5.32.0-31-gbf7152f'", '-o', 'dist/wsvpn-linux-arm64', './wsvpn']' returned non-zero exit status 1.
Error: Go build wsvpn-linux-armv5
Traceback (most recent call last):
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 473, in main
    task.join()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 204, in join
    raise self.exc
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 192, in run
    self._run()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 227, in _run
    check_call_addenv([self.gocmd, "build", "-trimpath", "-ldflags",
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 148, in check_call_addenv
    return check_call(args, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'build', '-trimpath', '-ldflags', "-w -s -X 'github.com/Doridian/wsvpn/shared.Version=v5.32.0-31-gbf7152f'", '-o', 'dist/wsvpn-linux-armv5', './wsvpn']' returned non-zero exit status 1.
Error: Go build wsvpn-linux-armv6
Traceback (most recent call last):
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 473, in main
    task.join()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 204, in join
    raise self.exc
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 192, in run
    self._run()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 227, in _run
    check_call_addenv([self.gocmd, "build", "-trimpath", "-ldflags",
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 148, in check_call_addenv
    return check_call(args, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'build', '-trimpath', '-ldflags', "-w -s -X 'github.com/Doridian/wsvpn/shared.Version=v5.32.0-31-gbf7152f'", '-o', 'dist/wsvpn-linux-armv6', './wsvpn']' returned non-zero exit status 1.
Error: Go build wsvpn-linux-armv7
Traceback (most recent call last):
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 473, in main
    task.join()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 204, in join
    raise self.exc
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 192, in run
    self._run()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 227, in _run
    check_call_addenv([self.gocmd, "build", "-trimpath", "-ldflags",
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 148, in check_call_addenv
    return check_call(args, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'build', '-trimpath', '-ldflags', "-w -s -X 'github.com/Doridian/wsvpn/shared.Version=v5.32.0-31-gbf7152f'", '-o', 'dist/wsvpn-linux-armv7', './wsvpn']' returned non-zero exit status 1.
Error: Go build wsvpn-linux-mips
Traceback (most recent call last):
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 473, in main
    task.join()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 204, in join
    raise self.exc
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 192, in run
    self._run()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 227, in _run
    check_call_addenv([self.gocmd, "build", "-trimpath", "-ldflags",
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 148, in check_call_addenv
    return check_call(args, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'build', '-trimpath', '-ldflags', "-w -s -X 'github.com/Doridian/wsvpn/shared.Version=v5.32.0-31-gbf7152f'", '-o', 'dist/wsvpn-linux-mips', './wsvpn']' returned non-zero exit status 1.
Error: Go build wsvpn-linux-mips-softfloat
Traceback (most recent call last):
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 473, in main
    task.join()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 204, in join
    raise self.exc
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 192, in run
    self._run()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 227, in _run
    check_call_addenv([self.gocmd, "build", "-trimpath", "-ldflags",
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 148, in check_call_addenv
    return check_call(args, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'build', '-trimpath', '-ldflags', "-w -s -X 'github.com/Doridian/wsvpn/shared.Version=v5.32.0-31-gbf7152f'", '-o', 'dist/wsvpn-linux-mips-softfloat', './wsvpn']' returned non-zero exit status 1.
Error: Go build wsvpn-linux-mipsle
Traceback (most recent call last):
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 473, in main
    task.join()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 204, in join
    raise self.exc
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 192, in run
    self._run()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 227, in _run
    check_call_addenv([self.gocmd, "build", "-trimpath", "-ldflags",
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 148, in check_call_addenv
    return check_call(args, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'build', '-trimpath', '-ldflags', "-w -s -X 'github.com/Doridian/wsvpn/shared.Version=v5.32.0-31-gbf7152f'", '-o', 'dist/wsvpn-linux-mipsle', './wsvpn']' returned non-zero exit status 1.
Error: Go build wsvpn-linux-mipsle-softfloat
Traceback (most recent call last):
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 473, in main
    task.join()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 204, in join
    raise self.exc
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 192, in run
    self._run()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 227, in _run
    check_call_addenv([self.gocmd, "build", "-trimpath", "-ldflags",
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 148, in check_call_addenv
    return check_call(args, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'build', '-trimpath', '-ldflags', "-w -s -X 'github.com/Doridian/wsvpn/shared.Version=v5.32.0-31-gbf7152f'", '-o', 'dist/wsvpn-linux-mipsle-softfloat', './wsvpn']' returned non-zero exit status 1.
Error: Go build wsvpn-linux-mips64
Traceback (most recent call last):
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 473, in main
    task.join()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 204, in join
    raise self.exc
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 192, in run
    self._run()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 227, in _run
    check_call_addenv([self.gocmd, "build", "-trimpath", "-ldflags",
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 148, in check_call_addenv
    return check_call(args, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'build', '-trimpath', '-ldflags', "-w -s -X 'github.com/Doridian/wsvpn/shared.Version=v5.32.0-31-gbf7152f'", '-o', 'dist/wsvpn-linux-mips64', './wsvpn']' returned non-zero exit status 1.
Error: Go build wsvpn-linux-mips64le
Traceback (most recent call last):
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 473, in main
    task.join()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 204, in join
    raise self.exc
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 192, in run
    self._run()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 227, in _run
    check_call_addenv([self.gocmd, "build", "-trimpath", "-ldflags",
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 148, in check_call_addenv
    return check_call(args, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'build', '-trimpath', '-ldflags', "-w -s -X 'github.com/Doridian/wsvpn/shared.Version=v5.32.0-31-gbf7152f'", '-o', 'dist/wsvpn-linux-mips64le', './wsvpn']' returned non-zero exit status 1.
Error: Go build wsvpn-darwin-amd64
Traceback (most recent call last):
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 473, in main
    task.join()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 204, in join
    raise self.exc
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 192, in run
    self._run()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 227, in _run
    check_call_addenv([self.gocmd, "build", "-trimpath", "-ldflags",
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 148, in check_call_addenv
    return check_call(args, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'build', '-trimpath', '-ldflags', "-w -s -X 'github.com/Doridian/wsvpn/shared.Version=v5.32.0-31-gbf7152f'", '-o', 'dist/wsvpn-darwin-amd64', './wsvpn']' returned non-zero exit status 1.
Error: Go build wsvpn-darwin-arm64
Traceback (most recent call last):
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 473, in main
    task.join()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 204, in join
    raise self.exc
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 192, in run
    self._run()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 227, in _run
    check_call_addenv([self.gocmd, "build", "-trimpath", "-ldflags",
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 148, in check_call_addenv
    return check_call(args, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'build', '-trimpath', '-ldflags', "-w -s -X 'github.com/Doridian/wsvpn/shared.Version=v5.32.0-31-gbf7152f'", '-o', 'dist/wsvpn-darwin-arm64', './wsvpn']' returned non-zero exit status 1.
Error: Go build wsvpn-windows-amd64.exe
Traceback (most recent call last):
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 473, in main
    task.join()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 204, in join
    raise self.exc
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 192, in run
    self._run()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 227, in _run
    check_call_addenv([self.gocmd, "build", "-trimpath", "-ldflags",
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 148, in check_call_addenv
    return check_call(args, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'build', '-trimpath', '-ldflags', "-w -s -X 'github.com/Doridian/wsvpn/shared.Version=v5.32.0-31-gbf7152f'", '-o', 'dist/wsvpn-windows-amd64.exe', './wsvpn']' returned non-zero exit status 1.
Error: Go build wsvpn-windows-386.exe
Traceback (most recent call last):
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 473, in main
    task.join()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 204, in join
    raise self.exc
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 192, in run
    self._run()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 227, in _run
    check_call_addenv([self.gocmd, "build", "-trimpath", "-ldflags",
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 148, in check_call_addenv
    return check_call(args, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'build', '-trimpath', '-ldflags', "-w -s -X 'github.com/Doridian/wsvpn/shared.Version=v5.32.0-31-gbf7152f'", '-o', 'dist/wsvpn-windows-386.exe', './wsvpn']' returned non-zero exit status 1.
Error: Go build wsvpn-windows-arm64.exe
Traceback (most recent call last):
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 473, in main
    task.join()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 204, in join
    raise self.exc
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 192, in run
    self._run()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 227, in _run
    check_call_addenv([self.gocmd, "build", "-trimpath", "-ldflags",
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 148, in check_call_addenv
    return check_call(args, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'build', '-trimpath', '-ldflags', "-w -s -X 'github.com/Doridian/wsvpn/shared.Version=v5.32.0-31-gbf7152f'", '-o', 'dist/wsvpn-windows-arm64.exe', './wsvpn']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 489, in <module>
    main()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 480, in main
    raise Exception("One or more tasks had errors!")
Exception: One or more tasks had errors!
``

**Comment by Doridian** [comment]
You have errors which indivate `stat /home/python/Venv/WSVPN/wsvpn/wsvpn: directory not found`

However, the Python script is `/home/python/Venv/WSVPN/wsvpn/./build.py`

This means that folder should exist, `build.py` is in the root of the repository and so is a folder called `wsvpn` (which contains a single file, `main.go`)
