### ISSUE TITLE
Enhancement request: option to force client to ignore TLS SNI checking of the server certificate.

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#30]
Please add the option on the client to allow it to ignore the TLS SNI checking of the server certificate.   The client may be in an environment that blocks DNS traffic (or sinks it to its own very restrictive DNS server).  The server IP may be not static (but sequentially predictable in a certain range).  I can't use a hostname/FQDN in such case.

**Comment by Doridian** [comment]
I added the option `server-name` in TLS client config yaml in 3.7.0
This should be able to fill your use-case.

Before setting server-name:
```
doridian@Fennec:/mnt/c/Users/Doridian/Programming/wsvpn$ cat client.yml
client:
  server: "webtransport://localhost:9000"
  tls:
    ca: cert.pem
doridian@Fennec:/mnt/c/Users/Doridian/Programming/wsvpn$ sudo ./cl
2022/07/11 12:15:21 Local version is: dev (protocol 8)
2022/07/11 12:15:21 base.go:76: [CLIENT-UNSET] WARNING: Connecting to webtransport://localhost:9000 with authentications: NONE
2022/07/11 12:15:21 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
panic: CRYPTO_ERROR (0x12a): x509: certificate is valid for text.com, not localhost

goroutine 1 [running]:
main.main()
        /mnt/c/Users/Doridian/Programming/wsvpn/client/main.go:112 +0x965
```

After setting server-name:
```
doridian@Fennec:/mnt/c/Users/Doridian/Programming/wsvpn$ cat client.yml
client:
  server: "webtransport://localhost:9000"
  tls:
    ca: cert.pem
    server-name: text.com
doridian@Fennec:/mnt/c/Users/Doridian/Programming/wsvpn$ sudo ./cl
2022/07/11 12:15:34 Local version is: dev (protocol 8)
2022/07/11 12:15:34 base.go:76: [CLIENT-UNSET] WARNING: Connecting to webtransport://localhost:9000 with authentications: NONE
2022/07/11 12:15:34 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2022/07/11 12:15:34 connection.go:55: [CLIENT-UNSET] Command serialization: json
2022/07/11 12:15:34 connection.go:59: [CLIENT-UNSET] TLS 1.3 WebTransport connection established with cipher=TLS_AES_128_GCM_SHA256
2022/07/11 12:15:34 ping.go:48: [CLIENT-UNSET] Ping enabled with interval 30s and timeout 5s
2022/07/11 12:15:34 commands.go:60: [CLIENT-UNSET] Remote version is: dev (protocol 8)
2022/07/11 12:15:34 commands.go:73: [CLIENT-UNSET] Got reply to command ID 524eb867-2890-4e48-bc41-76aa2fafb8b8 (ok): OK
2022/07/11 12:15:34 commands.go:58: [CLIENT-f5cf0fe0-65be-4798-8161-166820d2b9aa] Network mode TUN, Subnet 192.168.3.2/24, MTU 1216, IPConfig enabled
2022/07/11 12:15:34 commands.go:74: [CLIENT-f5cf0fe0-65be-4798-8161-166820d2b9aa] Opened tun1
2022/07/11 12:15:34 commands.go:87: [CLIENT-f5cf0fe0-65be-4798-8161-166820d2b9aa] Configured interface, starting operations
```

**Comment by vochong** [comment]
Wow! Awesome.  Thanks so much Mark.
